### ISSUE TITLE
MKL support

### ISSUE THREAD

**Issue by maxscheurer** [adc-connect/adcc#16]
Enable support for MKL.

- "normal" MKL from an Intel installation
- conda-provided MKL

**Comment by mfherbst** [comment]
One should add that this needs to be done mainly in `adccore` and then appropriate `adccore` binaries need to be available ...

This actually makes this a bit of an issue for me, because building adccore **once** per OS is kind of ok, I think, but once for MKL and once for some other BLAS. That accumulates quickly in the amount of time needed to deploy and the amount of space / traffic needed on the distribution hardware. So we should think twice about our options before going down that path.

**Comment by maxscheurer** [comment]
Yes, good point.

I think we should stick to only deploying the BLAS version for the time being.
MKL support would probably be nice to have for conda deployment, but other than that, we don't need it at the moment.

**Comment by mfherbst** [comment]
All right, then I'll try to get it to work for the source builds just to have it ready.

**Comment by maxscheurer** [comment]
I guess we just need to expose the MKL feature to the Python layer/`setup.py` now?

**Comment by mfherbst** [comment]
Yeah ... since we need a matching numpy I guess the easiest is to query `numpy.__config__` from the `setup.py` and react appropriately. I could get to that this week. (It's more tricky than one thinks at first, because you cannot assume `numpy` is installed when the setup.py runs for the first time).

**Comment by maxscheurer** [comment]
Yes.. and one cannot simply install it via pip, because you'd get the non-MKL version then 😄
